site_name: AI Battle Framework API Documentation
site_description: Comprehensive API documentation for the AI Battle framework
site_author: AI Battle Framework Team

repo_url: https://github.com/yourusername/ai-battle
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append(".")
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_if_no_docstring: true
            show_signature_annotations: true
            show_category_heading: true

nav:
  - Home: index.md
  - Core Components:
    - Overview: api/core/index.md
    - ConversationManager: api/core/conversation_manager.md
    - Adaptive Instructions: api/core/adaptive_instructions.md
  - Configuration System:
    - Overview: api/configuration/index.md
    - Configuration Classes: api/configuration/config_classes.md
    - YAML Integration: api/configuration/yaml_integration.md
  - Model Clients:
    - Overview: api/model_clients/index.md
    - BaseClient: api/model_clients/base_client.md
    - Model-Specific Clients: api/model_clients/specific_clients.md
  - File Handling:
    - Overview: api/file_handling/index.md
    - FileMetadata: api/file_handling/file_metadata.md
    - ConversationMediaHandler: api/file_handling/media_handler.md
  - Metrics & Analysis:
    - Overview: api/metrics/index.md
    - MetricsAnalyzer: api/metrics/metrics_analyzer.md
    - TopicAnalyzer: api/metrics/topic_analyzer.md
  - Arbiter System:
    - Overview: api/arbiter/index.md
    - ConversationArbiter: api/arbiter/conversation_arbiter.md
    - AssertionGrounder: api/arbiter/assertion_grounder.md
  - Utilities:
    - Overview: api/utilities/index.md
    - MemoryManager: api/utilities/memory_manager.md
    - Helper Functions: api/utilities/helper_functions.md
  - Usage Examples:
    - Basic Usage: api/examples/basic_usage.md
    - Configuration-Driven: api/examples/configuration_driven.md
    - File-Based Discussions: api/examples/file_based.md
    - Metrics Collection: api/examples/metrics_collection.md
  - API Reference: api/reference.md